### ISSUE TITLE
Problikávání fotek na SERPU

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#14]
při doteku na fotku profinautů na serpu, ta fotka problikne. ruší to

**Comment by havlenao** [comment]
Muzu pozadat o printscreen kde? Jedna se o iOS, pripadne jaka verze?

**Comment by MichalKalousek** [comment]
Vláďo doplň více koukali jsem na to a nevíme o co ti jde

**Comment by vladakali** [comment]
Screenshotem se tohle nedá poslat - je to probliknutí při tapnutí a scrolování seznamem Profinautů. iOS, nejnovější - číslo jsem nikde nedohledal.

**Comment by vladakali** [comment]
bikání je vidět tady: https://dl.dropboxusercontent.com/u/768126/SERP.MOV
