### ISSUE TITLE
Nekozistence verified vs guarantees

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#16]
Na SERPu mluvíme o verified ale na profilu používáme guarantees. Slaďme to pls. Guarantees mi přijde silnější a lepší.

**Comment by havlenao** [comment]
Jardo, muzes nam teda popsat finalni podobu?

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start

**Comment by jardacerny** [comment]
Ahoj, tak texty prosím upravit takto:

--------

Search různé varianty:

1 Profinaut recommends
2 Profinauts recommend
Adam and 1 other Profinaut recommend
Adam, Michal, Tomáš and 3 other Profinauts recommend
Adam recommends

--------

Profil:

Recommendations:
Your contacts  l  Other Profinauts
Adam Hazdra recommends Jana
