### ISSUE TITLE
SERP - řádek s garnaty, když je jen jeden člověk

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#17]
Používáme copy: " Vladimír Kalinay and 0 other people..." To je imo blbý. Lepší by bylo ukázat jen "Vladimír Kalinay guarantees Martin."

**Comment by adamhazdra** [comment]
přidávám se

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start
