### ISSUE TITLE
BIO je nečitelné

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#18]
Pls nezarovnávejme BIO do bloku- Zarovnejme do leva.
Plus zvětšme trochu řádkování, umožněme tvorbu odstaců.
Mrkněte třeba na BIO Jiří Suchý. Není jedinej, kdo ho má nečitelné.

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start
