### ISSUE TITLE
Other Profinauts vs. You contacts

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#19]
Hoj, když jsem na profilu člověka, tak vidím, že já a další 2 lidi v mých kontaktech garantují člověka. V záložce From Profinauts je ale NULA. To je divný. Spíš bych pojmenoval tu záložku "Other Profinauts", pak by dávalo smysl, že je tam 0.

**Comment by adamhazdra** [comment]
souhlasím a přidávám se

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start

**Comment by jardacerny** [comment]
ahoj, popis viz issue #16
