### ISSUE TITLE
Vizuální detail: Překrývání stránek z prava

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#20]
Při proklikávání mezi profilama lidí, je animace nové stránky z prava nepříjemná pro oči- horní modrej pruh bývá různě vysokej. Osobně preferuju načtení nové stránky bez této microanimace.

**Comment by havlenao** [comment]
S Michalem jsme neprisli na to, co je vlastne spatne. Muzes to zkusit lip popsat/poslat screen/video?

**Comment by vladakali** [comment]
video jsem nahrál sem: https://www.dropbox.com/sh/ilet830674ryshs/AABmksahlSuChL2vwrV_fgJ6a?dl=0
