### ISSUE TITLE
Chybí textura z prototypu na první obrazovce, onboarding screenech, v hlavičce a na profilu

### ISSUE THREAD

**Issue by adamhazdra** [ViableOne/profinaut_issues#22]
![screen shot 2017-02-24 at 20 29 21](https://cloud.githubusercontent.com/assets/25667202/23317749/fb24fe88-facf-11e6-8083-bdbdae2c7231.png)

![screen shot 2017-02-24 at 20 04 47](https://cloud.githubusercontent.com/assets/25667202/23317049/305d14a8-facd-11e6-9d36-b794f5f64ca1.png)
![screen shot 2017-02-24 at 20 04 33](https://cloud.githubusercontent.com/assets/25667202/23317050/30624c66-facd-11e6-966f-13bd00511466.png)

Nyní je pouze barva

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start
