### ISSUE TITLE
1 people verified na výpise výsledků je špatně

### ISSUE THREAD

**Issue by adamhazdra** [ViableOne/profinaut_issues#23]
Profinauti, kteří mají pouze jedno doporučení od člověka, který není v mých kontaktech, mají na výpise uvedeno "1 people verified". People je množné číslo, správně pro případ právě jednoho doporučení je "1 person verified", či lépe ještě "1 Profinaut verified"

![img_1524](https://cloud.githubusercontent.com/assets/25667202/23317236/d7c9da1e-facd-11e6-82dc-dae5e0850210.PNG)

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start 
dle zadáno od Jardy v BC

**Comment by jardacerny** [comment]
ahoj, popsáno v issue #16
