### ISSUE TITLE
Copy přepínače pro povolení kontaktů je špatně

### ISSUE THREAD

**Issue by adamhazdra** [ViableOne/profinaut_issues#26]
You se v angličtině nepíše s velkým Y jako v češtině. Ve všech případech musí být malé. totéž platí na profilu, pokud nemá uživatel povolené kontakty, také tam prosím you a your vždy s malým.

![img_1526](https://cloud.githubusercontent.com/assets/25667202/23317819/455d95a0-fad0-11e6-8eb0-1a422f9a9edc.PNG)

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start
