### ISSUE TITLE
Profinaut doporučuje sám sebe - Adam guarantees Adam

### ISSUE THREAD

**Issue by adamhazdra** [ViableOne/profinaut_issues#27]
Vyskytuje se pouze u nás 5 zakladatelů (hazdra, kalinay, černý, grynhoff, kalousek), ale je to divné - Adam Hazdra guarantees Adam by tam nemělo být, sám sebe nedoporučuji.

![img_1528](https://cloud.githubusercontent.com/assets/25667202/23318081/499ef068-fad1-11e6-9e30-9cdb9c986737.PNG)

**Comment by havlenao** [comment]
Opraveno v DB, je to tak ale v excelu, ktery se importoval. Osetrime to na urovni aplikace.

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start
