### ISSUE TITLE
V apce máme kategorii UX design i UI design.

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#30]
IMO to je zbytečný. Navrhuju nechat v apce jen kategorii UX design. 
UI design se navíc ani nepoužívá - pokud ano, tak jako ID = interakční design.

**Comment by havlenao** [comment]
@jardacerny je zapotrebi teda ten skill vymazat z toho excelu s profinautama

**Comment by jardacerny** [comment]
Ahoj, dlouhodobě udržitelné je mít možnost "párovat" podobné výrazy. Tozn. dát si do podobných např. "UX, UX design, UI, UI design, interakční design". Potom v searchi zobrazovat celou tuto grupu, pokud někdo vybere jeden z těchto skillů.

To že jeden výraz odstraníme nic neřeší, naopak z pohledu searche to je krok zpět, protože tam nenajdu co hledam.

Co myslíte?

**Comment by vladakali** [comment]
Asi jsem grammar nazi, ale UI design bych fakt zahodil. Ale principielně s tebou Jardo souhlasím.
