### ISSUE TITLE
Nahodne mizi/nenacitaji se fotky

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#39]
Na Serpu Adam nemel fotku. Kdyz jsem dal zpet a pak jsem se vratil do kategorie, fotka se nacetla v pohode. Divny. Imo by se to melo nacitat korektne vzdy.

**Comment by havlenao** [comment]
To je kvuli tomu, ze to bylo v appce naceshovane jeste pred tim nez se udelala oprava db. Reseni je aplikaci killnout (idealne preinstalovat - nekdy se ty bety s oficialni apkou muzou tlouct) a uz by to nemelo delat.

**Comment by vladakali** [comment]
už to vypadá ok
