### ISSUE TITLE
Chyby při vyhledávání čárky 

### ISSUE THREAD

**Issue by MichalKalousek** [ViableOne/profinaut_issues#40]
neumí vyhledávat s čárkama viz příklad 
![img_0109](https://cloud.githubusercontent.com/assets/25532126/23767842/5a9d610e-050a-11e7-80af-33e8c8e9e133.JPG)
![img_0110](https://cloud.githubusercontent.com/assets/25532126/23767858/688c117a-050a-11e7-8505-6174611b9283.JPG)

**Comment by havlenao** [comment]
Poresime.
