### ISSUE TITLE
na seznamu není fotka a v detailu ano 

### ISSUE THREAD

**Issue by MichalKalousek** [ViableOne/profinaut_issues#41]
![img_0113](https://cloud.githubusercontent.com/assets/25532126/23772234/82a8426c-051a-11e7-96fe-aae7b019283e.PNG)
![img_0111](https://cloud.githubusercontent.com/assets/25532126/23772236/848a2d2a-051a-11e7-91a9-ca1da2d7b00d.PNG)

**Comment by havlenao** [comment]
Porad?

**Comment by vladakali** [comment]
já už se s tím nesetkávám

**Comment by MichalKalousek** [comment]
Uz nee

Michal Kalousek

On 10 Mar 2017, at 12:29, havlenao <notifications@github.com<mailto:notifications@github.com>> wrote:


Porad?
