### ISSUE TITLE
Nesedí mi počty doporučených na SERPu a v Profilu

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#42]
Na SERPu mám 4 doporučení, a v detailu 6. Co teda platí? :-)

**Comment by havlenao** [comment]
muzes poslat screen? Ja u tebe vidim na SERPU i detailu 6 doporuceni. Mas povolene kontakty?

**Comment by vladakali** [comment]
Adam má taky stejnej trabl. Týká se to asi jen když koukám sám na sebe jako Profinaut.
![img_4219](https://cloud.githubusercontent.com/assets/25950081/23799293/50c32544-05a8-11e7-98ee-717054b75264.png)
![img_4220](https://cloud.githubusercontent.com/assets/25950081/23799294/50e34c5c-05a8-11e7-8d0c-b2a468b06d23.png)

**Comment by havlenao** [comment]
Ok to je chyba, omezujeme ten pocet vyjmenovanych lidi z kontaktu na 3, kdyz jich mas vic, tak ty pocty pak nesedi. Opravime.
