### ISSUE TITLE
Po vymazání searche nezajždí klávesnice

### ISSUE THREAD

**Issue by adamhazdra** [ViableOne/profinaut_issues#44]
ozval se nám jeden uživatel. osobně považuji za triviální a neopravoval bych v tuto chvíli
![screen shot 2017-03-17 at 10 15 54](https://cloud.githubusercontent.com/assets/25667202/24036670/dd89dd54-0afa-11e7-8cd9-230b35e0ca23.png)

**Comment by havlenao** [comment]
Klavesnici jsme trosku poladili v nove beta verzi (zakryvala nekdy vysledky), nicmene v tomto pripade staci kliknout na tlacitko "Hledat" a klavesnice zajede (nativni chovani v iOSu)...nedava smysl, abysme ji skryvaly kdyz smaze hledane slovo, ptz by pak nemohl zase psat...nebo se mylim? Snad jsem nic neprehlednul.

**Comment by vladakali** [comment]
Taky bych ji po smazáni slova neskrýval. IMO je tohle chování správně. Moje hypotéza je, že když už jdeš psát keyword a smažeš ho, tak budeš chctít psát jiné slovo... Proto by úprava, kterou navrhuje užovka byla spíš na obtíž.
