### ISSUE TITLE
Appka padá na androidu po odeslání feedbacku 

### ISSUE THREAD

**Issue by MichalKalousek** [ViableOne/profinaut_issues#45]
Dvakrát jsem viděl u někoho spadnout appku po odeslaní feedbacku nebo se tam zaseknout. Primárně jsem viděl na Androidu. Dnes Maruška také psala, že si to někdo říkal

M.

**Comment by havlenao** [comment]
Je to chyba react native frmw. Oprava by mela byt venku pristi tyden, tak to pak updatneme.
