### ISSUE TITLE
Ztrojená notifikace

### ISSUE THREAD

**Issue by vladakali** [ViableOne/profinaut_issues#46]
Martin Mráz psal SMS Antonovi Titovovi a přišli mu druhej den 3 notifikace na 1 akci.
![img_4589](https://cloud.githubusercontent.com/assets/25950081/24401591/48987296-13b5-11e7-9c4c-29593ba008dd.png)
iPhone 7plus

**Comment by vladakali** [comment]
hele koukám na datumy a asi je to bug nějaký lednový verze... ale možná to tam pořád máme zabugovaný. Tak při volný chvíli pls check:-)

**Comment by MilosChmelar** [comment]
To samé se opakovaně stalo mně v minulém i tomto týdnu.
iPhone SE iOS 11.0.1

**Comment by havlenao** [comment]
na jake verzi? Nova verze uz notifikace na sms nema.

**Comment by MilosChmelar** [comment]
Pravděpodobně 3.0.0. Ale dnes jsem appku přeinstalovával, takže se to už nedozvím. Zároveň si nejsem jistý, zda to byla notifikace na sms nebo na volání - spíše to bylo na volání. To už ale také nezjistím, protože po přeinstalaci mám seznam notifikací prázdný. 

Tak to asi neřeš a uvidím, zda se to bude opakovat.
