### ISSUE TITLE
Network error u aplikace na pozadi

### ISSUE THREAD

**Issue by MilosChmelar** [ViableOne/profinaut_issues#51]
Kdyz necham apku na pozadi (jsem na wifi) a zvovu ji aktivuji (na mobilnich datech), zobrazi se network error.

iOS, iPhone SE

**Comment by MilosChmelar** [comment]
Screenshot prilozim..

**Comment by havlenao** [comment]
Cau, muzes pls presne popsat na jakych screenech jses a jednotlive kroky? Nedari se nam to zreprodukovat. Mas LTE?

**Comment by MilosChmelar** [comment]
Screenshot:
![img_2172](https://user-images.githubusercontent.com/32699095/33009030-a5d09da0-cdd5-11e7-8d27-7b8627ea8b5a.PNG)

Aplikaci jsem měl otevřenou když jsem byl připojený na firemní (LMC) wifi. Apku jsem shodil na pozadí a odebral se z práce domů. V tramvaji (když se telefon automatick odchodem z práce přepojil na data) jsem apku zaktivoval a zobrazila se mi hláška ze screenshotu.

**Comment by MilosChmelar** [comment]
Dost často se mi také stávalo, že se aktivaci do popředí se v apkce zobrazil červený pruh s hláškou že není připojení k internetu (ačkoliv jsem připojený byl). Musel jsem udělat nějakou akci (překliknout na jinou navigační záložku) aby hláška zmizela.

**Comment by MilosChmelar** [comment]
Dnes mi Maruška říkala, že se jí to také stalo.

**Comment by MilosChmelar** [comment]
Dnes (15:45) se to stalo i Michalovi Kalouskovi, mel apku na pozadi a byl stale na stejne siti (Direct People)
