### ISSUE TITLE
Message se občas nezobrazí - iOS

### ISSUE THREAD

**Issue by MilosChmelar** [ViableOne/profinaut_issues#53]
Dostal jsem zpětnou vazbu od Vládi Kalinaye (iOS), že se mu nekteré zprávy nezobrazují. Zobrazí se mu až po gestu slide-up. Jako by byly schované pod page-foldem.

**Comment by MilosChmelar** [comment]
Dnes se mi to také stalo. Flow: Z deeplinku jsem se dostal do přeheldu zpráv od uživatelů a klikl na poslední zprávu Vládi Kalinaye. Poslední zprávu jsem mu poslal já. V okně se nezobrazila žádná zpráva. Vrátil jsem se na výpis a znovu otevřel chat s Vláďou, zprávy se už zobrazily.

**Comment by havlenao** [comment]
Tak zatim uspesna jen reprodukce na iOS. Na androidu se Vam to taky podarilo?

**Comment by MilosChmelar** [comment]
Na androidu to asi bude jiný problém. Viz issue https://github.com/ViableOne/profinaut_issues/issues/52
nezobrazují se mu žádné zprávy
