### ISSUE TITLE
Messages - dvě časová razítka, jedna zpráva

### ISSUE THREAD

**Issue by MilosChmelar** [ViableOne/profinaut_issues#54]
Vláďovi přišly dvě zprávy (asi), ale zobrazila se mu jen jedna. Je možné, že se Ondrovi podařilo odeslat prázdnou zprávu? 

Viz příloha:
![image uploaded from ios](https://user-images.githubusercontent.com/32699095/33010966-b3b206c8-cddc-11e7-8b45-c154c105200c.png)

**Comment by havlenao** [comment]
K nam doputovala jedna prazdna:
![image](https://user-images.githubusercontent.com/25053699/33015561-81fad7ea-cdeb-11e7-8b7a-1816c31c6312.png)

co ma za mobil?

**Comment by MilosChmelar** [comment]
Android 7.0, Huawei Nova

Když bude potřeba, požádám ho o kontakt.
