### ISSUE TITLE
Missing Profinaut

### ISSUE THREAD

**Issue by jardacerny** [ViableOne/profinaut_issues#9]
na výsledcích hledání na konci seznamu button "Missing Profinaut?"
Po tapnutí sdola vyjede modál v designu Feedbacku

Obsah modálu:
místo fotky šedivý avatar
nadpis "Missing Profinaut?"
area s placeholderem "Who do you need for your project?"
input na tel s placeholderem "Your phone number"
tlačítko "Send"

**Comment by MichalKalousek** [comment]
Bude v release 13 ale ven jdeme s 12 nebude tedy na start

**Comment by MichalKalousek** [comment]
Mail na VIP@Profinaut.com
